server:
  port: 8080
  servlet:
    context-path: /api
  error:
    whitelabel:
      enabled: false
spring:
  profiles:
    active: dev
  datasource:
    url: jdbc:mysql://localhost:3306/addressbook?createDatabaseIfNotExist=true&useSSL=false&useUnicode=true&characterEncoding=UTF-8&useJDBCCompliantTimezoneShift=true&useLegacyDatetimeCode=false&serverTimezone=CET
    username: root
    password: root
  jpa:
    show-sql: true
    generate-ddl: false
    hibernate:
      ddl-auto: create
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL5InnoDBDialect
        format_sql: true
  messages:
    use-code-as-default-message: true
    